/* Auto-generated by cbindgen. Do not edit. */

#ifndef IROH_SWIFT_H
#define IROH_SWIFT_H

/* Warning: this file is auto-generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Configuration for creating a node.
 */
typedef struct IrohNodeConfig {
    /**
     * Path to the blob store directory (required).
     */
    const char *storage_path;
    /**
     * Whether to use n0's public relay servers (default: true).
     */
    bool relay_enabled;
} IrohNodeConfig;

/**
 * Opaque handle to an Iroh node.
 *
 * The actual IrohNode is stored in a Box, and this handle holds
 * a raw pointer to that Box.
 */
typedef struct IrohNodeHandle {
    uint8_t _private[0];
} IrohNodeHandle;

/**
 * Callback for node creation.
 */
typedef struct IrohNodeCreateCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with the node handle.
     */
    void (*on_success)(void *userdata, struct IrohNodeHandle *handle);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohNodeCreateCallback;

/**
 * Borrowed bytes from Swift (read-only view into Swift memory).
 */
typedef struct IrohBytes {
    const uint8_t *data;
    uintptr_t len;
} IrohBytes;

/**
 * Callback for operations that return a string on success.
 *
 * NOTE: Callbacks run on a Tokio worker thread. Swift must safely
 * resume continuations from that context.
 */
typedef struct IrohCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with a C string (caller must free with `iroh_string_free`).
     */
    void (*on_success)(void *userdata, const char *result);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohCallback;

/**
 * Owned bytes returned to Swift (must be freed with `iroh_bytes_free`).
 */
typedef struct IrohOwnedBytes {
    uint8_t *data;
    uintptr_t len;
    uintptr_t capacity;
} IrohOwnedBytes;

/**
 * Callback for operations that return bytes on success.
 */
typedef struct IrohGetCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with owned bytes (caller must free with `iroh_bytes_free`).
     */
    void (*on_success)(void *userdata, struct IrohOwnedBytes bytes);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohGetCallback;

/**
 * Create a new Iroh node asynchronously.
 *
 * # Safety
 * - `config.storage_path` must be a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_node_create(struct IrohNodeConfig config, struct IrohNodeCreateCallback callback);

/**
 * Destroy an Iroh node and free its resources.
 *
 * This performs a graceful shutdown, ensuring pending writes are flushed.
 *
 * # Safety
 * - `handle` must be a valid pointer returned by `iroh_node_create`
 * - `handle` must not be used after this call
 */
void iroh_node_destroy(struct IrohNodeHandle *handle);

/**
 * Add bytes to the blob store and get a shareable ticket.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `bytes.data` must point to valid memory for `bytes.len` bytes
 * - `callback` must have valid function pointers
 */
void iroh_put(const struct IrohNodeHandle *handle,
              struct IrohBytes bytes,
              struct IrohCallback callback);

/**
 * Download bytes from a ticket.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `ticket` must be a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_get(const struct IrohNodeHandle *handle,
              const char *ticket,
              struct IrohGetCallback callback);

/**
 * Free a string returned by Iroh functions.
 *
 * # Safety
 * - `s` must be a pointer returned by an Iroh function, or null
 * - `s` must not be used after this call
 */
void iroh_string_free(char *s);

/**
 * Free bytes returned by `iroh_get`.
 *
 * # Safety
 * - `bytes` must have been returned by `iroh_get`
 * - The bytes must not be used after this call
 */
void iroh_bytes_free(struct IrohOwnedBytes bytes);

#endif  /* IROH_SWIFT_H */
