/* Auto-generated by cbindgen. Do not edit. */

#ifndef IROH_SWIFT_H
#define IROH_SWIFT_H

/* Warning: this file is auto-generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Configuration for creating a node.
 */
typedef struct IrohNodeConfig {
    /**
     * Path to the blob store directory (required).
     */
    const char *storage_path;
    /**
     * Whether to use relay servers (default: true).
     */
    bool relay_enabled;
    /**
     * Custom relay URL (null to use n0's public relays).
     * Must be a valid URL like "https://relay.example.com".
     */
    const char *custom_relay_url;
} IrohNodeConfig;

/**
 * Opaque handle to an Iroh node.
 *
 * The actual IrohNode is stored in a Box, and this handle holds
 * a raw pointer to that Box.
 */
typedef struct IrohNodeHandle {
    uint8_t _private[0];
} IrohNodeHandle;

/**
 * Callback for node creation.
 */
typedef struct IrohNodeCreateCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with the node handle.
     */
    void (*on_success)(void *userdata, struct IrohNodeHandle *handle);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohNodeCreateCallback;

/**
 * Borrowed bytes from Swift (read-only view into Swift memory).
 */
typedef struct IrohBytes {
    const uint8_t *data;
    uintptr_t len;
} IrohBytes;

/**
 * Callback for operations that return a string on success.
 *
 * NOTE: Callbacks run on a Tokio worker thread. Swift must safely
 * resume continuations from that context.
 */
typedef struct IrohCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with a C string (caller must free with `iroh_string_free`).
     */
    void (*on_success)(void *userdata, const char *result);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohCallback;

/**
 * Owned bytes returned to Swift (must be freed with `iroh_bytes_free`).
 */
typedef struct IrohOwnedBytes {
    uint8_t *data;
    uintptr_t len;
    uintptr_t capacity;
} IrohOwnedBytes;

/**
 * Callback for operations that return bytes on success.
 */
typedef struct IrohGetCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with owned bytes (caller must free with `iroh_bytes_free`).
     */
    void (*on_success)(void *userdata, struct IrohOwnedBytes bytes);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohGetCallback;

/**
 * Progress information for a download operation.
 */
typedef struct IrohDownloadProgress {
    /**
     * Bytes downloaded so far.
     */
    uint64_t downloaded;
    /**
     * Total bytes expected (0 if unknown).
     */
    uint64_t total;
} IrohDownloadProgress;

/**
 * Callback for get operations with progress reporting.
 */
typedef struct IrohGetProgressCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called with progress updates during download.
     */
    void (*on_progress)(void *userdata, struct IrohDownloadProgress progress);
    /**
     * Called on success with owned bytes (caller must free with `iroh_bytes_free`).
     */
    void (*on_success)(void *userdata, struct IrohOwnedBytes bytes);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohGetProgressCallback;

/**
 * Information about an Iroh node.
 */
typedef struct IrohNodeInfo {
    /**
     * Node ID as a string (caller must free with `iroh_string_free`).
     */
    const char *node_id;
    /**
     * Relay URL if connected (caller must free with `iroh_string_free`).
     * Null if not connected to a relay.
     */
    const char *relay_url;
    /**
     * Whether the node is connected to the network.
     */
    bool is_connected;
} IrohNodeInfo;

/**
 * Callback for node info retrieval.
 */
typedef struct IrohNodeInfoCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called on success with node info.
     */
    void (*on_success)(void *userdata, struct IrohNodeInfo info);
    /**
     * Called on failure with an error message (caller must free with `iroh_string_free`).
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohNodeInfoCallback;

/**
 * Parsed ticket information.
 */
typedef struct IrohTicketInfo {
    /**
     * Whether the ticket is valid.
     */
    bool is_valid;
    /**
     * The blob hash as a string (caller must free with `iroh_string_free`).
     * Null if invalid.
     */
    const char *hash;
    /**
     * The node ID from the ticket (caller must free with `iroh_string_free`).
     * Null if invalid.
     */
    const char *node_id;
    /**
     * Whether this is a recursive (collection) ticket.
     */
    bool is_recursive;
} IrohTicketInfo;

/**
 * Callback for ticket validation.
 */
typedef struct IrohTicketValidateCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called with validation result. Always called (never fails).
     */
    void (*on_complete)(void *userdata, struct IrohTicketInfo info);
} IrohTicketValidateCallback;

/**
 * Callback for node close operation.
 */
typedef struct IrohCloseCallback {
    /**
     * Opaque pointer passed back to Swift.
     */
    void *userdata;
    /**
     * Called when close completes successfully.
     */
    void (*on_complete)(void *userdata);
    /**
     * Called if close fails with an error message.
     */
    void (*on_failure)(void *userdata, const char *error);
} IrohCloseCallback;

/**
 * Options for put/get operations.
 */
typedef struct IrohOperationOptions {
    /**
     * Timeout in milliseconds (0 = no timeout).
     */
    uint64_t timeout_ms;
} IrohOperationOptions;

/**
 * Create a new Iroh node asynchronously.
 *
 * # Safety
 * - `config.storage_path` must be a valid null-terminated UTF-8 string
 * - `config.custom_relay_url` must be null or a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_node_create(struct IrohNodeConfig config, struct IrohNodeCreateCallback callback);

/**
 * Destroy an Iroh node and free its resources.
 *
 * This performs a graceful shutdown, ensuring pending writes are flushed.
 *
 * # Safety
 * - `handle` must be a valid pointer returned by `iroh_node_create`
 * - `handle` must not be used after this call
 */
void iroh_node_destroy(struct IrohNodeHandle *handle);

/**
 * Add bytes to the blob store and get a shareable ticket.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `bytes.data` must point to valid memory for `bytes.len` bytes
 * - `callback` must have valid function pointers
 */
void iroh_put(const struct IrohNodeHandle *handle,
              struct IrohBytes bytes,
              struct IrohCallback callback);

/**
 * Download bytes from a ticket.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `ticket` must be a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_get(const struct IrohNodeHandle *handle,
              const char *ticket,
              struct IrohGetCallback callback);

/**
 * Free a string returned by Iroh functions.
 *
 * # Safety
 * - `s` must be a pointer returned by an Iroh function, or null
 * - `s` must not be used after this call
 */
void iroh_string_free(char *s);

/**
 * Free bytes returned by `iroh_get`.
 *
 * # Safety
 * - `bytes` must have been returned by `iroh_get`
 * - The bytes must not be used after this call
 */
void iroh_bytes_free(struct IrohOwnedBytes bytes);

/**
 * Download bytes from a ticket with progress reporting.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `ticket` must be a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_get_with_progress(const struct IrohNodeHandle *handle,
                            const char *ticket,
                            struct IrohGetProgressCallback callback);

/**
 * Get information about the node.
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `callback` must have valid function pointers
 */
void iroh_node_info(const struct IrohNodeHandle *handle, struct IrohNodeInfoCallback callback);

/**
 * Validate and parse a ticket string.
 *
 * This function always succeeds - check `info.is_valid` for the result.
 *
 * # Safety
 * - `ticket` must be a valid null-terminated UTF-8 string (or null)
 * - `callback` must have valid function pointers
 */
void iroh_validate_ticket(const char *ticket, struct IrohTicketValidateCallback callback);

/**
 * Explicitly close a node and free its resources asynchronously.
 *
 * This is preferred over `iroh_node_destroy` when you need to await
 * graceful shutdown completion.
 *
 * # Safety
 * - `handle` must be a valid pointer returned by `iroh_node_create`
 * - `handle` must not be used after this call
 * - `callback` must have valid function pointers
 */
void iroh_node_close(struct IrohNodeHandle *handle, struct IrohCloseCallback callback);

/**
 * Add bytes to the blob store with options (e.g., timeout).
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `bytes.data` must point to valid memory for `bytes.len` bytes
 * - `callback` must have valid function pointers
 */
void iroh_put_with_options(const struct IrohNodeHandle *handle,
                           struct IrohBytes bytes,
                           struct IrohOperationOptions options,
                           struct IrohCallback callback);

/**
 * Download bytes from a ticket with options (e.g., timeout).
 *
 * # Safety
 * - `handle` must be a valid node handle
 * - `ticket` must be a valid null-terminated UTF-8 string
 * - `callback` must have valid function pointers
 */
void iroh_get_with_options(const struct IrohNodeHandle *handle,
                           const char *ticket,
                           struct IrohOperationOptions options,
                           struct IrohGetCallback callback);

#endif  /* IROH_SWIFT_H */
